- README.md
> Docs - Improving Readme

- README.md
> Docs - Add Project Setup Checklist

- README.md
> #7-adding yes flag to researched and decided in readme for jest

- README.md
> #5-adding researched and decided flag to readme for cypress

- README.md
> #16-adding researched and decided flags to readme for react testing library

- README.md
> #17-adding react-google-login info to README

- README.md
Closes #23 
Also, James is fantastic
> #23-Adding AWS info as database provider to readme

- README.md
After doing a bit of research detailed in #2, I think it's safe to decide on Prisma for the ORM.
> Decided on Prisma for ORM

- .github/workflows/main.yml
Created directory for GitHub workflows. Copied in and customized a basic workflow to run all Jest tests on pushes and PRs to the main branch.
> Added basic main workflow for running Jest tests

- README.md
Major changes are because of prettier formatting to make the table readable in the editor. Closes #24
> Mark lint and format as implemented

- package.json
- src/backend/functions/example.ts
Clean out the package.json of unnecessary fields, update incorrect info, and fill in missing info for package.json. Closes #75
> Updated Packaged.json

- src/backend/functions/projects.ts
- src/backend/prisma/schema.prisma
- src/backend/tests/projects.test.ts
- src/react-app-env.d.ts
- src/reportWebVitals.ts
- src/setupTests.ts
- src/shared/axios.ts
Added license snippets to various different files. Also replaced duplicate type interface definition with utils package import since otherwise lint would complain. Closes #76
> Add license snippets

- src/App.tsx
- src/pages/page-not-found/page-not-found.module.css
- src/pages/page-not-found/page-not-found.test.tsx
- src/pages/page-not-found/page-not-found.tsx
> #89 - Added 404 page to redirect invalid URLs

- src/App.tsx
- src/pages/login/login.module.css
- src/pages/login/login.test.tsx
- src/pages/login/login.tsx
Created the login component and temporarily wired it in with the rest of the app on the `/login` url. Currently the login button just takes you to the home page. Closes #120
> Create Login Page

- src/backend/functions/users.ts
- src/backend/tests/users.test.ts
I've updated the users endpoint to now return just the dummy data from the utils package. Added tests for the endpoint handler
> Updated Users API Endpoint

- src/shared/routes.ts
Closes #92. Created centralized file in shared folder for defining front-end routes.
> Added central frontend routes file

- src/utils/src/api-routes.ts
- src/utils/src/index.ts
Added a file to the utils package for use in centralizing route definition for the api routes.
> Added central api routes file

- package-lock.json
- package.json
- src/App.css
- src/App.test.tsx
- src/App.tsx
- src/components/nav-notifications-menu/nav-notifications-menu.module.css
- src/components/nav-notifications-menu/nav-notifications-menu.test.tsx
- src/components/nav-notifications-menu/nav-notifications-menu.tsx
- src/components/nav-page-links/nav-page-links.module.css
- src/components/nav-page-links/nav-page-links.test.tsx
- src/components/nav-page-links/nav-page-links.tsx
- src/components/nav-top-bar/nav-top-bar.module.css
- src/components/nav-top-bar/nav-top-bar.test.tsx
- src/components/nav-top-bar/nav-top-bar.tsx
- src/components/nav-user-menu/nav-user-menu.module.css
- src/components/nav-user-menu/nav-user-menu.test.tsx
- src/components/nav-user-menu/nav-user-menu.tsx
I decided to give it a shot using the react-bootstrap library of components to build a top fixed navigation. I also added nav links as a temporary option before the sidebar nav gets finished in #104. The logo should get changed out with #106. closes #59
> Created top navigation bar

- src/App.test.tsx
- src/App.tsx
- src/index.tsx
- src/pages/login/login.module.css
- src/pages/login/login.tsx
Lifted the browser router up into the `index.tsx` file in order to allow the login page to be displayed without the top navigation bar. Potentially will want to rethink the top-most layers of `index.tsx > App.tsx > pages...` given that the items necessary at the `index.tsx` level will increase over time. Things like react context and testing the top-most level will potentially get a little tricky, and it seems like not the best practice to have a lot of logic in `index.tsx`.
> Lifted the router up to index.tsx for authentication

- src/utils/src/types/change-request-types.ts
Fixed the little spelling mistake
> Fix manufacturing spelling mistake

- package-lock.json
- package.json
Updated Prisma. See #128 for details.
> Update Prisma to 2.19.0

- src/backend/functions/work-packages.ts
- src/backend/tests/work-packages.test.ts
- src/utils/src/dummy-data.ts
closes #71
Create Dummy Work Package Endpoint
> Create Dummy Work Package Endpoint

- package-lock.json
> Fix npm audit vulnerabiltity

- docs/Onboarding.md
Add sections and database initialization section to Onboarding doc. Closes #95
> Add sections and database initialization section to Onboarding doc

- src/backend/functions/projects.ts
- src/backend/tests/projects.test.ts
- src/utils/src/api-routes.ts
Add API_URL to utils and updated projects endpoint. Closes #151
> Add API_URL to utils and updated projects endpoint

- src/app/app-main/app-main.tsx
- src/components/work-package-details/work-package-details.module.css
- src/components/work-package-details/work-package-details.test.tsx
- src/components/work-package-details/work-package-details.tsx
Attached is a screenshot of the component I put together. I mainly based the design off of the work package summary component I had created for #91 . Let me know of any design changes that need to be made on this.
Also, I passed in a work package as a prop for the component but it does not seem to have a field for the project name. Is there an easy way to access this? Should the component take in a project as well? Thanks! Closes #72
> #72 - Created Work Package Details Component

- src/backend/functions/users.ts
- src/backend/tests/users.test.ts
- src/utils/src/api-routes.ts
Added routeMatcher to users endpoint. Added single user route to API routes. Closes #148
> Add routeMatcher to users endpoint

- src/backend/functions/change-requests.ts
- src/backend/functions/projects.ts
- src/backend/functions/users.ts
- src/backend/tests/change-requests.test.ts
- src/backend/tests/projects.test.ts
- src/backend/tests/users.test.ts
- src/backend/tests/work-packages.test.ts
- src/utils/src/api-utils.ts
The tests in the backend were failing due to issues with JSON stringification and handling of error cases. I fixed them and updated the API to stringify all response bodies and have error cases always be an object with a message field. Closes #176
> Fixing all the tests

- package-lock.json
- package.json
- src/backend/functions/change-requests.ts
- src/backend/functions/projects.ts
- src/backend/functions/users.ts
- src/backend/functions/work-packages.ts
- src/backend/tests/change-requests.test.ts
- src/backend/tests/projects.test.ts
- src/backend/tests/users.test.ts
- src/utils/package-lock.json
- src/utils/package.json
- src/utils/src/api-utils.ts
- src/utils/src/dummy-data.ts
- src/utils/src/types/api-utils-types.ts
- src/utils/tests/api-utils.test.ts
- Updated API with new Netlify function types (closes #181)
- Expanded work packages endpoint with routeMatcher pattern (closes #169)
- Create and integrate API response object factory functions (closes #110)
> Update API types and add factory functions

- src/backend/functions/work-packages.ts
- src/backend/tests/work-packages.test.ts
- added single work package lookup
- expanded test cases
- Closes #187
> Expanded work package API endpoint with single work package lookup

- src/components/description-list/description-list.module.css
- src/components/description-list/description-list.test.tsx
- src/components/description-list/description-list.tsx
> #156 - created the description list component

- src/app/app-main/app-main.tsx
- src/components/description-list/description-list.tsx
- src/components/work-package-changes/work-package-changes.module.css
- src/components/work-package-changes/work-package-changes.test.tsx
- src/components/work-package-changes/work-package-changes.tsx
There were a few errors and stuff, so I refactored and fixed some components. Closes #211.
> Clean up linting errors

- src/app/app-authenticated/app-authenticated.test.tsx
- src/app/app-authenticated/app-authenticated.tsx
- src/app/app-main/app-main.test.tsx
- src/components/change-request-details/change-request-details.tsx
- src/components/project-details/project-details.tsx
- src/pages/home/home.module.css
- src/pages/home/home.test.tsx
- src/pages/home/home.tsx
I've gotten everything except for the testing for the home page down. I want to display the user's name, but I can't seem to pass that in anywhere.
> 219- home page component

- src/app/app-authenticated/app-authenticated.test.tsx
- src/app/app-main/app-main.test.tsx
- src/components/nav-user-menu/nav-user-menu.test.tsx
- src/components/work-package-dependencies/work-package-dependencies.test.tsx
- src/components/work-package-dependencies/work-package-dependencies.tsx
- src/components/work-package-summary/work-package-summary.test.tsx
- src/components/work-package-summary/work-package-summary.tsx
- src/pages/change-request-details/change-request-details.test.tsx
- src/pages/change-requests/change-requests.test.tsx
- src/pages/home/home.test.tsx
- src/pages/login/login.test.tsx
- src/pages/wbs-details/wbs-details.test.tsx
- src/test-support/test-utils.tsx
closed #158 
Update to Use React-Router Link
> Project - Update to Use React-Router Link

- src/shared/pipes.tsx
I've gone ahead and added the code to work the three pipes requested by this issue, which can be found at the bottom of the file
> I138  leroy - adding 3 pipes

- src/backend/functions/change-requests.ts
- src/backend/functions/projects.ts
- src/backend/functions/users.ts
- src/backend/functions/work-packages.ts
- src/utils/src/api-utils.ts
- src/utils/tests/api-utils.test.ts
Refactored and expanded various parts of the API Utils. Closes #235
> #235 expand api utils

- docs/ContributorGuide.md
- docs/Onboarding.md
various little updates to the docs that are long overdue. closes #233
> #233 update docs

- docs/ProductManagement.md
- docs/Requirements.md
Filled out and expanded the product management documentation in the hopes of better clarifying the expected behavior, goals, intentions, etc. for the project and the product. This new documentation can hopefully be used to help explain what we are building and why we are building it. Closes #240.
> #240 update product mgmt docs

- src/components/shared/loading-indicator/loading-indicator.module.css
- src/components/shared/loading-indicator/loading-indicator.test.tsx
- src/components/shared/loading-indicator/loading-indicator.tsx
Created the loading indicator. Will still need to implement everywhere.
> #253 - Created loading indicator

- src/components/app/app-context/app-context.test.tsx
- src/components/app/app-context/app-context.tsx
Oops, I forgot to add this. Pretty important since it makes all the hooks work. Closes #249.
> #249 - Add query client provider

- src/components/change-requests/change-request-details/change-request-details.test.tsx
- src/components/change-requests/change-request-details/change-request-details.tsx
- src/components/change-requests/change-requests-table/change-requests-table.test.tsx
- src/components/change-requests/change-requests-table/change-requests-table.tsx
- src/components/projects/projects-table/projects-table.test.tsx
- src/components/projects/projects-table/projects-table.tsx
- src/components/projects/wbs-details/project-container/project-container.test.tsx
- src/components/projects/wbs-details/project-container/project-container.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.tsx
Implemented the loading indicator component in a bunch of places. Closes #253.
> #253 - Implement loading indicator

- src/components/home/home.tsx
- src/components/projects/projects-table/projects-table.module.css
- src/components/projects/projects.module.css
- src/components/projects/projects.tsx
- src/components/projects/wbs-details/wbs-details.tsx
- src/components/shared/error-page/error-page.module.css
- src/components/shared/error-page/error-page.tsx
Assorted styling stuff.
Closes #254. Closes #242.
> Misc styling

- src/components/app/app-authenticated/app-authenticated.tsx
- src/components/change-requests/change-requests.tsx
- src/components/projects/projects.tsx
- src/components/settings/settings.module.css
- src/components/settings/settings.test.tsx
- src/components/settings/settings.tsx
- src/shared/routes.ts
Created and implemented settings page, very barebones. Also did some refactoring. Closes #201.
> #201 settings page

- src/components/app/app-authenticated/app-authenticated.test.tsx
- src/components/change-requests/change-requests-table/change-requests-table/change-requests-table.test.tsx
- src/components/change-requests/change-requests-table/change-requests-table/change-requests-table.tsx
- src/components/change-requests/change-requests.module.css
- src/components/change-requests/change-requests.test.tsx
- src/components/change-requests/change-requests.tsx
- src/components/home/home.module.css
- src/components/home/home.test.tsx
- src/components/home/home.tsx
- src/components/projects/projects-table/projects-table.test.tsx
- src/components/projects/projects-table/projects-table/projects-table.tsx
- src/components/projects/wbs-details/project-container/project-container.module.css
- src/components/projects/wbs-details/project-container/project-container.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.tsx
- src/components/shared/page-title/page-title.module.css
- src/components/shared/page-title/page-title.test.tsx
- src/components/shared/page-title/page-title.tsx
Standardize the page titles with a shared component. Closes #207.
> #207 consistent titles

- src/components/change-requests/change-request-details/change-request-details/change-request-details.module.css
- src/components/change-requests/change-request-details/change-request-details/change-request-details.test.tsx
- src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
- src/components/projects/wbs-details/project-container/project-container.module.css
- src/components/projects/wbs-details/project-container/project-container.test.tsx
- src/components/projects/wbs-details/project-container/project-container.tsx
- src/components/projects/wbs-details/project-container/project-details/project-details.module.css
- src/components/projects/wbs-details/project-container/project-details/project-details.test.tsx
- src/components/projects/wbs-details/project-container/project-details/project-details.tsx
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.module.css
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.tsx
- src/components/projects/wbs-details/work-package-container/description-list/description-list.module.css
- src/components/projects/wbs-details/work-package-container/description-list/description-list.tsx
- src/components/projects/wbs-details/work-package-container/work-package-changes/work-package-changes.module.css
- src/components/projects/wbs-details/work-package-container/work-package-changes/work-package-changes.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-changes/work-package-changes.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.tsx
- src/components/projects/wbs-details/work-package-container/work-package-dependencies/work-package-dependencies.module.css
- src/components/projects/wbs-details/work-package-container/work-package-dependencies/work-package-dependencies.tsx
- src/components/projects/wbs-details/work-package-container/work-package-details/work-package-details.module.css
- src/components/projects/wbs-details/work-package-container/work-package-details/work-package-details.tsx
- src/components/projects/wbs-details/work-package-container/work-package-rules/work-package-rules.module.css
- src/components/projects/wbs-details/work-package-container/work-package-rules/work-package-rules.tsx
- src/components/shared/page-block/page-block.module.css
- src/components/shared/page-block/page-block.test.tsx
- src/components/shared/page-block/page-block.tsx
- src/components/shared/page-title/page-title.test.tsx
- src/components/shared/page-title/page-title.tsx
refactored tons of front-end styling and boxes to ensure there is just one central box style being used. closes #206.
> #206 consistent box styling

- src/components/whole-app/login/login.tsx
- src/services/tests/users.hooks.test.tsx
- src/services/users.hooks.ts
Initial step towards linking UI and API for authentication. Got the mutation hook working, but need to actually test the new functionality and hoping to get the updates from the immediate previous PR.
> #247 - Refactor and link login to API

- src/test-support/test-data/wbs-numbers.stub.ts
- src/utils/src/validate-wbs.ts
- src/utils/tests/validate-wbs.test.ts
added tests and changed wbsnumber equality function name to be more specific
> #244 dylan pham

- src/components/change-requests/change-requests-table/change-requests-table/change-requests-table.tsx
- src/components/projects/projects-table/projects-table/projects-table.tsx
closes #271 changing mouse hovering effect for project table into nice finger
> #271 - changing mouse hovering effect for project table into nice finger

- src/components/change-requests/change-requests-table/change-requests-table.test.tsx
- src/components/change-requests/change-requests-table/change-requests-table/change-requests-table.test.tsx
- src/components/change-requests/change-requests-table/change-requests-table/change-requests-table.tsx
- src/components/change-requests/change-requests.test.tsx
- src/components/change-requests/change-requests.tsx
- src/components/change-requests/new-change-request/new-change-request-page/new-change-request-page.module.css
- src/components/change-requests/new-change-request/new-change-request-page/new-change-request-page.test.tsx
- src/components/change-requests/new-change-request/new-change-request-page/new-change-request-page.tsx
- src/components/change-requests/new-change-request/new-change-request.module.css
- src/components/change-requests/new-change-request/new-change-request.test.tsx
- src/components/change-requests/new-change-request/new-change-request.tsx
- src/components/shared/action-button/action-button.module.css
- src/components/shared/action-button/action-button.test.tsx
- src/components/shared/action-button/action-button.tsx
- src/components/shared/page-title/page-title.module.css
- src/components/shared/page-title/page-title.tsx
- src/components/whole-app/nav-top-bar/nav-top-bar.tsx
Created the page structure and placeholder text for submitting new change requests page.
Closes #196.
> #196 submit new cr page

- src/components/change-requests/new-change-request/new-change-request-page/common-form-fields/common-form-fields.module.css
- src/components/change-requests/new-change-request/new-change-request-page/common-form-fields/common-form-fields.test.tsx
- src/components/change-requests/new-change-request/new-change-request-page/common-form-fields/common-form-fields.tsx
- src/components/change-requests/new-change-request/new-change-request-page/new-change-request-page.tsx
> #192 - Create CR common form fields component

- src/backend/prisma/schema.prisma
- src/backend/prisma/seed-data/projects.ts
- src/backend/prisma/seed.ts
- src/components/projects/wbs-details/project-container/project-container.tsx
- src/services/projects.api.ts
- src/test-support/test-data/projects.stub.ts
- src/utils/src/dummy-data.ts
- src/utils/src/types/project-types.ts
Add support for other constraints as a description bullet array on projects. Utilizing existing description bullet definition to provide metadata for when the bullet is added or removed.
> #289 add other constraints

- src/backend/prisma/schema.prisma
- src/backend/prisma/seed-data/work-packages.ts
- src/backend/prisma/seed.ts
- src/components/projects/wbs-details/work-package-container/description-list/description-list.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.tsx
- src/services/work-packages.api.ts
- src/test-support/test-data/work-packages.stub.ts
- src/utils/src/dummy-data.ts
- src/utils/src/types/project-types.ts
Rename description to expected activities. Closes #290.
> #290 convert description to expected activities

- src/backend/prisma/schema.prisma
- src/backend/prisma/seed-data/projects.ts
- src/backend/prisma/seed.ts
- src/components/projects/wbs-details/project-container/project-container.tsx
- src/services/projects.api.ts
- src/services/work-packages.api.ts
- src/test-support/test-data/projects.stub.ts
- src/utils/src/dummy-data.ts
- src/utils/src/types/project-types.ts
Add features array. Refactoring type transformer functions to reduce code duplication. Closes #288.
> #288 add features

- src/backend/prisma/schema.prisma
- src/backend/prisma/seed-data/work-packages.ts
- src/backend/prisma/seed.ts
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.test.tsx
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.tsx
- src/components/projects/wbs-details/work-package-container/work-package-details/work-package-details.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-details/work-package-details.tsx
- src/services/work-packages.api.ts
- src/test-support/test-data/work-packages.stub.ts
- src/utils/src/dummy-data.ts
- src/utils/src/types/project-types.ts
Convert deliverables in work package to an array of description bullets. Closes #264.
> #264 convert deliverables to array

- src/backend/prisma/migrations/20210815191721_init/migration.sql
- src/backend/prisma/seed-data/change-requests.ts
- src/components/projects/wbs-details/project-container/project-container.tsx
- src/test-support/test-data/projects.stub.ts
- src/utils/src/dummy-data.ts
- src/utils/src/types/project-types.ts
Enable changes to be registered on projects in addition to work packages. Closes #297.
> #297 changes on projects

- package-lock.json
- package.json
- src/backend/functions/users.ts
- src/backend/prisma/migrations/20210828191914_init/migration.sql
- src/backend/prisma/schema.prisma
- src/backend/prisma/seed-data/users.ts
- src/backend/tests/users.test.ts
- src/components/app/app-public/app-public.test.tsx
- src/components/projects/projects-table/projects-table/projects-table.test.tsx
- src/services/auth.hooks.ts
- src/services/tests/users.api.test.ts
- src/services/tests/users.hooks.test.tsx
- src/services/users.api.ts
- src/services/users.hooks.ts
- src/shared/pipes.tsx
- src/shared/types.ts
- src/test-support/test-data/test-utils.stub.ts
- src/test-support/test-data/users.stub.ts
- src/utils/src/types/user-types.ts
Switch to merging into feature branch. Similar to #324. Closes #214. Replaces #323.
> #214 connect users db

- src/components/change-requests/new-change-request/new-change-request-page/new-change-request-page.tsx
- src/components/change-requests/new-change-request/new-change-request-page/stage-gate-form-fileds/stage-gate-form-fields.module.css
- src/components/change-requests/new-change-request/new-change-request-page/stage-gate-form-fileds/stage-gate-form-fields.test.tsx
- src/components/change-requests/new-change-request/new-change-request-page/stage-gate-form-fileds/stage-gate-form-fields.tsx
> #195 - Stage Gate Change Request Form Fields 

- src/components/projects/wbs-details/project-container/project-container.tsx
- src/test-support/test-data/projects.stub.ts
- src/utils/src/dummy-data.ts
- src/utils/src/types/project-types.ts
We added summary to the Project page below the project details as a PageBlock and changed the Project type to include the summary. We also updated the dummy data to include dummy summary data.
> #320 - Add Summary to Project type & page

- src/test-support/test-utils.tsx
Updated WBS regular expression to accomodate numbers 0-99 for the first digit.
> #268 - Updated WBS regular expression

- docs/ContributorGuide.md
Adds a few lines in the contributor guide on how to run tests with npm
> #330 - added instructions on how to run tests with npm commands

- src/components/projects/projects-table/projects-table/projects-table.test.tsx
- src/components/projects/projects-table/projects-table/projects-table.tsx
- src/components/projects/projects-table/projects-table/wbsNumSort.test.ts
- src/utils/tests/wbsNumSort.test.ts
We've resolved all of the issues that were presented in #96. The first one, centering the tables, was pretty simple to fix, just adding headerAlign = 'center' to each column and changing the align from 'left' to 'center'. To fix the version sorting, we had to override the default sorting algorithm and implement our own with sortFunc. The only one I'm not sure about is the Duration sort, since it seems like it's already been resolved.
> #96 Projects Table Sorting

- package.json
- src/backend/functions/users.ts
- src/components/home/useful-links/useful-links.tsx
- src/components/projects/projects-table/projects-table/projects-table.tsx
- src/components/projects/wbs-details/work-package-container/dependencies-list/dependencies-list.test.tsx
- src/components/whole-app/login/login.tsx
- src/test-support/test-data/test-utils.stub.ts
We implemented most of the eslint configs. We tried to add the prefer-nullish-coallescing setting, but we couldn't get it to work.
> #154 - Implement eslint configs

- src/backend/functions/users.ts
- src/backend/functions/work-packages.ts
added the user transformer in users.ts
> #358 create users shared tools

- .github/ISSUE_TEMPLATE/bug-form.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/engineering-tasks.yml
- .github/ISSUE_TEMPLATE/epic.yml
- .github/ISSUE_TEMPLATE/new-feature.yml
- .github/ISSUE_TEMPLATE/other.yml
can't be tested until it's merged with main. This pr includes forms for:
- bug fixes
- new features
- other
with fields as described by the contributor guide
> #165 issue templates

- .github/ISSUE_TEMPLATE/bug-form.yml
- .github/ISSUE_TEMPLATE/engineering-tasks.yml
- .github/ISSUE_TEMPLATE/epic.yml
- .github/ISSUE_TEMPLATE/new-feature.yml
- .github/ISSUE_TEMPLATE/other.yml
Add more helpful formatting suggestions, information, and default values to issue templates
> #165 - Github Issue Template Improvements

- src/backend/functions/change-requests.ts
Allow change request endpoints to properly supply information to follow types for activation, stage gate, and standard scope change requests. Should take care of the bug from #383.
> #332 Add Backend Change Request Types Support

- docs/Onboarding.md
- docs/PrismaMigrationTools.md
We created the new PrismaMigrationsTool doc and updated the Onboarding document.
> #340-created-prisma-tools-doc-and-updated-onboarding

- src/backend/functions/work-packages.ts
Made the change to the copy and paste error noted in https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/issues/429#issuecomment-1009588853. I launched the app and confirmed that they deliverables now correctly appear. Not sure if there's any tests I need to update for this change.
> Fix deliverables getting data for expected activities

- src/components/projects/projects-table/projects-table.test.tsx
- src/utils/src/types/change-request-types.ts
- src/utils/src/types/project-types.ts
PR for my initial work on standardizing the enums. started by doing the standardization, but I haven't done anything more. I realize that I want to rename the front-end enums to match the back-end enums, but I think that's technically a separate ticket #435 which is part of epic #397. closes #419.
> Standardize enums

- src/backend/functions/change-requests-new.ts
- src/backend/functions/change-requests-review.ts
- src/backend/tests/change-requests-review.test.ts
- src/utils/src/api-routes.ts
This creates a change request review endpoint following the structure used in the new change request endpoint, validating the body and updating the change request in the database.
Closes #372.
> #372 - Change Request Review Endpoint

- package-lock.json
- package.json
- src/backend/functions/change-requests-review.ts
- src/components/change-requests/review-change-request/review-change-request.tsx
- src/components/change-requests/review-change-request/review-change-request/review-change-request.tsx
- src/services/change-requests.api.ts
- src/services/change-requests.hooks.ts
- src/shared/urls.ts
- src/utils/package-lock.json
- src/utils/package.json
- src/utils/src/types/change-request-types.ts
Wired together the change request review page on the front-end and the change request review back-end endpoint. Modified and lifted logic out of the display / view component so as to hold router and api connection logic in the parent component. 
Also, this required adding `json-schema-to-ts` as a dev dependency in order to make it be much much simpler. We will want to use this pattern continuing forward if it causes no issues in deployment.
Closes #371 
Change Request Table
Accepting a Change Request
Change Request Accepted
> wire change request reviewing

- src/backend/functions/change-requests-review.ts
- src/backend/functions/change-requests.ts
- src/backend/prisma/migrations/20220116033137_init/migration.sql
- src/backend/prisma/schema.prisma
- src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
- src/components/change-requests/change-request-details/change-request-details/review-notes/review-notes.test.tsx
- src/components/change-requests/change-request-details/change-request-details/review-notes/review-notes.tsx
- src/components/change-requests/review-change-request/review-change-request.tsx
- src/services/change-requests.api.ts
- src/services/change-requests.hooks.ts
- src/test-support/test-data/change-requests.stub.ts
- src/utils/src/types/change-request-types.ts
updated the full stack from database all the way through to the front-end to try and display who reviewed the change request along side the review notes. closes #453
> record cr reviewer

- src/backend/prisma/seed-data/change-requests.ts
- src/components/change-requests/change-requests-table/change-requests-table.tsx
- src/components/change-requests/change-requests-table/change-requests-table/change-requests-table.tsx
fix undefined vs false. closes #447
> cr table no

- docs/ContributorGuide.md
- docs/Onboarding.md
Added the necessary documentation to `Onboarding.md`
> #321 - When to push package.json?

- src/backend/functions/work-packages-create.ts
I think I fixed the bug but I can't run it to check because I'm having issues with my dev environment
> #486 - work package creation fails if project has no work packages

- src/components/projects/projects-table/projects-table-filter/projects-table-filter.test.tsx
- src/components/projects/projects-table/projects-table-filter/projects-table-filter.tsx
- src/components/projects/projects-table/projects-table.tsx
Made the status strings uppercase when they are being compared to the enums during filtering.
> #443 - Status Setting Bug

- README.md
- docs/OnboardingWindows.md
Created onboarding docs for Windows and updated the readme accordingly (the link in the readme should work once the PR is approved). Closes #497
> Onboarding Docs for Windows & Readme Edit

- src/components/projects/create-project-form/create-project-form.tsx
A majority of the validation necessary for the form was implemented in #465. I added extra validation on the inputs to limit the range of acceptable numbers and added template feedback elements for when the form fails (though the form never reaches this because the default form validation catches the errors before it can reach this point). 
A big drawback I found while working on this ticket is that a lot of the in-depth validation I would want to do (e.g. making sure the change request ID actually exists, the car number exists, etc.) would require an external library so we don't make the component messy with validation logic. The react bootstrap docs uses [Formik](https://formik.org/), which seems to be fairly popular, and there is also [react-hook-form](https://react-hook-form.com/) if …
> #495 Create project form validation

- src/backend/functions/projects.ts
- src/backend/functions/work-packages-create.ts
- src/backend/functions/work-packages-edit.ts
- src/backend/tests/work-packages-edit.test.ts
- src/utils/src/api-routes.ts
- src/utils/src/types/work-package-types.ts
I added the main functionality and tested inputs only. I haven't done any sort of testing to make sure it works yet.
One issue is that how can I determine if an expected activity or deliverable has been edited since there is no id attached to them? As of now I've left that part out.
> #368 work package edit endpoint

- src/backend/functions/change-requests-new.ts
- src/backend/functions/change-requests-review.ts
- src/backend/functions/projects-new.ts
- src/backend/functions/work-packages-create.ts
- src/backend/functions/work-packages-edit.ts
- src/utils/src/api-utils.ts
- src/utils/src/types/api-utils-types.ts
- src/utils/src/types/change-request-types.ts
- src/utils/src/types/project-types.ts
- src/utils/src/types/work-package-types.ts
This start adds support functions for schemas with middy lambdas. The goal is to add the typings to all the backend middy functions.
> #488 - Add Middy Schema Typings

- src/backend/functions/work-packages-create.ts
- src/backend/tests/work-packages-create.test.ts
- src/components/projects/create-wp-form/create-wp-form.tsx
- src/components/projects/create-wp-form/create-wp-form/create-wp-form.test.tsx
- src/components/projects/create-wp-form/create-wp-form/create-wp-form.tsx
- src/services/work-packages.api.ts
- src/services/work-packages.hooks.ts
- src/shared/urls.ts
- src/test-support/test-data/test-utils.stub.ts
- src/utils/src/types/api-utils-types.ts
- src/utils/src/types/work-package-types.ts
Need review, will clean up chicken scratch code when I get back from work. Still need to fix `work-package-create` tests to conform to the new schema that uses WBS Numbers instead of project ID.
> #468 wire up create wp form

- src/components/projects/create-project-form/create-project-form.test.tsx
- src/components/projects/create-project-form/create-project-form.tsx
- src/components/projects/create-project-form/create-project-form/create-project-form.test.tsx
- src/components/projects/create-project-form/create-project-form/create-project-form.tsx
- src/services/projects.api.ts
- src/services/projects.hooks.ts
- src/services/work-packages.hooks.ts
- src/shared/urls.ts
Fairly straight forward, made the api call, custom react hook, and used states to connect the form data to `handleSubmit`. For future wire up tickets, I'd suggest adding in the tickets to try to use the available payload schemas we now have as that significantly simplifies the code.
> #467 wire up create project form

- src/components/projects/create-project-form/create-project-form.tsx
- src/components/projects/create-wp-form/create-wp-form.tsx
Pretty self-explanatory. Minor user experience improvement. Manually tested and it works. Closes #543.
> Add loading indicator to create project form and create work package form

- src/backend/functions/change-requests.ts
Fixes #541 
we were just supplying the wrong WBS num in the back-end. now it works beautifully
> #541 - Supply correct wbsNum to implemented changes

- .github/pull_request_template.md
Adding PR template.
I got impatient and decided to do this myself cuz I think it'll help with improving PRs.
Closes #457
> #457 - Add GitHub pull request template

- .github/pull_request_template.md
Add couple more items per @RChandler234's suggestions, particularly mentioning `package-lock.json`
Closes #457. Actually this time tho
> #457 - Add missing items to PR checklist

- .github/ISSUE_TEMPLATE/spike.yml
Added a Github issue template for spike tickets.
I based the structure of the template off what I did for #545. The labeling of the sections could probably use improvement though.
None
_Any remaining things that need to get done_
None
Closes # (issue #)
> #546 add spike ticket issue template

- src/components/change-requests/new-change-request/new-change-request-page/common-form-fields/common-form-fields.tsx
Fixed options available in the Change Request dropdown. Mapped ChangeRequestType values instead of list of strings
Created new branch without messy commit history as per James' request
> #485 - fixed options in Change Request dropdown

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- docs/Onboarding.md
Added settings.json that has the formatting settings and extensions.json that has all the recommended extensions.
I'm wondering if I should also update some of the documentation to reflect the changes made here. For example, in the onboarding set up I can say just click install all of recommended extensions since that will now pop-up because of the file. Also some of the format on save settings should be automatically set so that part of the section might not be necessary anymore.
Closes #536
> #536 - Add vscode folder with settings and extensions

- src/components/projects/project-edit-form/project-edit-container/edit-mode-options/edit-mode-options.module.css
- src/components/projects/project-edit-form/project-edit-container/project-edit-details/project-edit-details.module.css
- src/components/projects/projects-table/projects-table.module.css
- src/components/projects/projects-table/projects-table/projects-table.module.css
- src/components/projects/wbs-details/work-package-container/dependencies-list/dependency/dependency.module.css
- src/components/projects/wbs-details/work-package-container/work-package-container.module.css
- src/utils/tsconfig.json
Applied prettier to all files according to previously defined scripts.
All tests still pass. Manually tested and everything appeared to work.
No functionality changes, thus not applicable.
n/a
Closes #576
> Apply prettier to all files

- src/components/projects/project-edit-form/project-edit-container/edit-mode-options/edit-mode-options.tsx
- src/components/projects/project-edit-form/project-edit-container/project-edit-container.tsx
- src/components/projects/project-edit-form/project-edit-container/project-edit-details/project-edit-details.tsx
- src/components/projects/project-edit-form/project-edit-container/project-edit-summary/project-edit-summary.tsx
- src/components/shared/editable-text-input-list/editable-text-input-list.tsx
(Created new branch and pull request to fix commit messages)
Added validation to fields in the project edit form, by adding a validation function that checks the required fields when the form is submitted (on clicking the save button).
Used try/catch when creating a new URL object for link validation.
> Links don't seem to work without the prefix (like https://), so users would need to input links containing the prefix. The current validation checks for that.
Added "required" to the form component to ensure that fields aren't left empty.
N/A
N/A
*Budget Validation:*
*URL Validation:*
*Project Summary Validation:*
*Bullet Validation:*
Completed all points in issue.
Please review the [contributor …
> #370 Project Edit Form Validation

- src/components/change-requests/change-requests-table/change-requests-filter/change-requests-filter.module.css
- src/components/change-requests/change-requests-table/change-requests-filter/change-requests-filter.test.tsx
- src/components/change-requests/change-requests-table/change-requests-filter/change-requests-filter.tsx
Created a clear button to reset all filters for the Change Request table.
- Make sure clear button appears
- Make sure the clear button does not change when pressed
- Make sure clear resets parent state
Closes #525
> #525 - Create CR Table Clear Filter Button

- src/components/app/app-public/app-public.tsx
- src/components/whole-app/login/login.test.tsx
- src/components/whole-app/login/login.tsx
When a user clicks on a link in the website to open in a new tab, after logging in they are taken to the page they were trying to visit instead of previously being brought back to the home page.
Closes #404
> #404 - Post-Login Link Redirect

- package-lock.json
- package.json
- src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
- src/components/change-requests/change-requests.test.tsx
- src/components/change-requests/change-requests.tsx
- src/components/change-requests/review-change-request/review-change-request.test.tsx
- src/components/change-requests/review-change-request/review-change-request.tsx
- src/components/change-requests/review-change-request/review-change-request/review-change-request.test.tsx
- src/components/change-requests/review-change-request/review-change-request/review-change-request.tsx
- src/components/shared/form-validation-schemas/change-request-form-schemas.ts
Redirect merge from `main` to `upgrade-to-react-hook-forms`. See #580 for more details.
See #580 
See #580 
See #580
none
Closes # (issue #)
> #565 upgrade review change request form

- src/components/whole-app/nav-top-bar/nav-top-bar.tsx
added a slash to the image src
Closes #604
> #604 - Broken Logo Bug

- src/backend/functions/projects-edit.ts
- src/components/projects/project-edit-form/project-edit-container/project-edit-container.tsx
- src/components/projects/project-edit-form/project-edit-container/project-edit-details/project-edit-details.module.css
- src/components/projects/project-edit-form/project-edit-container/project-edit-details/project-edit-details.test.tsx
- src/components/projects/project-edit-form/project-edit-container/project-edit-details/project-edit-details.tsx
- src/components/projects/project-edit-form/project-edit-container/project-edit-summary/project-edit-summary.test.tsx
- src/components/projects/project-edit-form/project-edit-container/project-edit-summary/project-edit-summary.tsx
- src/components/projects/wbs-details/project-container/project-container.tsx
- src/services/projects.api.ts
- src/services/projects.hooks.ts
- src/shared/urls.ts
- src/utils/src/types/project-types.ts
Added the wiring up functionality as specified in the tickets. Not done with testing yet but want review on what I have so far. Manual testing shows that it works right.
have not tested yet
Closes #363
> #363 Wire Up Project Edit Form

- src/backend/functions/work-packages-edit.ts
- src/components/projects/wbs-details/work-package-container/work-package-container-edit.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/dependencies-list/dependencies-list.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/dependencies-list/dependencies-list.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/dependencies-list/dependency/dependency.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/dependencies-list/dependency/dependency.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/edit-mode-options/edit-mode-options.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-buttons/work-package-buttons.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-buttons/work-package-buttons.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-container-edit.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-container-view.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-container-view.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-details/work-package-details.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-details/work-package-details.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-edit-details/work-package-edit-details.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.tsx
- src/components/shared/bullet-list/bullet-list.test.tsx
- src/components/shared/bullet-list/bullet-list.tsx
- src/components/shared/editable-detail/editable-detail.test.tsx
- src/components/shared/editable-detail/editable-detail.tsx
- src/services/work-packages.api.ts
- src/services/work-packages.hooks.ts
- src/shared/pipes.tsx
- src/shared/urls.ts
- src/utils/src/types/api-utils-types.ts
- src/utils/src/types/work-package-types.ts
To be honest, I don't know half of what I did, but I got it to mostly work where it does update but you need to refresh the page to see the changes. It's 5 AM right now, so I have done zero tests and just want to be done with this ticket.
After working on this, I've realized how scuffed a lot of things are (including the things I've worked on), so can we look into a v3 post mvp and actually thoroughly plan out what packages we are going to use, how we are organizing the backend (MVC, etc.), what the relationship(s) between our data is, etc.?
- idk man
n/a
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/docs/ContributorGuide.md) and reach out to your squad if …
> #365 wire up work package edit form

- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-container-view.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-details/work-package-details.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-edit-details/work-package-edit-details.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.tsx
- src/components/shared/editable-detail/editable-detail.tsx
:yikes: This just gets rid of lint errors.
> #608 Get rid of all the lint errors

- src/components/projects/project-edit-form/project-edit-container/project-edit-container.tsx
- src/components/projects/project-edit-form/project-edit-container/project-edit-details/project-edit-details.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-container-edit.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-edit-details/work-package-edit-details.tsx
Add checks for undefined user set as current project manager / project lead for project / work package. Add emDash to represent undefined user. For work packages, gutted out state storing user names and looking up IDs, replaced with storing IDs directly.
n/a
- too lazy, mvp time
- too lazy, mvp time
_Any remaining things that need to get done_
idk, n/a for now
Closes #610
> #610 fix edit errors

- src/backend/functions/work-packages-create.ts
- src/backend/tests/work-packages-create.test.ts
Pretty straightforward. Used the implementation from projects-new to check if the CR is valid.
- When change request is not reviewed
- When change request doesn't exist
Closes #540
> #540 - Added checking of review

- src/components/whole-app/login/login-dev/login-dev.test.tsx
- src/components/whole-app/login/login-dev/login-dev.tsx
Replaced full list with a list containing one of each role.
Updated test to only expect 5 options instead of the previous 7.
Closes #402
> #402 - remove duplicate roles from dev login

- src/components/whole-app/login/login.tsx
nav to home if would otherwise circular redirect to login page
Closes #629
> #629 - fix stuck on login page

- src/backend/functions/change-requests.ts
- src/backend/functions/projects-new.ts
- src/backend/functions/projects.ts
- src/backend/functions/work-packages.ts
- src/backend/tests/projects.test.ts
- src/components/projects/create-wp-form/create-wp-form.tsx
- src/components/projects/projects-table/projects-table.tsx
- src/components/projects/projects-table/projects-table/projects-table.tsx
- src/components/projects/projects-table/projects-table/wbsNumSort.test.ts
- src/components/projects/wbs-details/work-package-page/work-package-edit-container/work-package-edit-container.tsx
- src/services/tests/projects.api.test.ts
- src/services/tests/work-packages.api.test.ts
- src/shared/pipes.tsx
- src/shared/tests/pipes.test.tsx
- src/test-support/test-data/change-requests.stub.ts
- src/test-support/test-data/projects.stub.ts
- src/test-support/test-data/wbs-numbers.stub.ts
- src/test-support/test-data/work-packages.stub.ts
- src/utils/src/types/project-types.ts
- src/utils/src/validate-wbs.ts
Standardize all `WbsNumber` to match the database in their field naming to include "Number".
No new tests, just updated existing ones.
Closes #639
> #639 standardize wbs num

- src/components/app/app-public/app-public.tsx
- src/components/change-requests/create-change-request/create-change-request-view/create-change-request-view.test.tsx
- src/components/change-requests/create-change-request/create-change-request-view/create-change-request-view.tsx
- src/components/change-requests/create-change-request/create-change-request.test.tsx
- src/components/change-requests/create-change-request/create-change-request.tsx
- src/components/projects/wbs-details/project-page/project-view-container/project-view-container.test.tsx
- src/components/projects/wbs-details/project-page/project-view-container/project-view-container.tsx
- src/components/projects/wbs-details/work-package-page/work-package-page.tsx
- src/components/projects/wbs-details/work-package-page/work-package-view-container/work-package-view-container.test.tsx
- src/components/projects/wbs-details/work-package-page/work-package-view-container/work-package-view-container.tsx
- src/components/whole-app/login/login.tsx
- src/services/utils.hooks.ts
- src/shared/routes.ts
enable pre-fill of wbsNumber on the create change request form for easy population from project or work package pages
tested enabling the button
on project page
populated from URL
on work package page
Closes #511
> #511 query params for create cr

- src/frontend/pages/WorkPackageDetailPage/work-package-edit-container/work-package-edit-container.tsx
> #659 - Delieverables fixed

- src/frontend/pages/ProjectDetailPage/project-view-container/project-view-container.tsx
sort work packages in summary view by start date for easier timeline view
Closes #671
> #671 - Sort WPs by start date

- src/frontend/components/editable-text-input-list/editable-text-input-list.tsx
fixed the bug where it scrolls down automatically when you start an edit form
manually check it by starting an edit form
> #608 - Edit Form Scroll Bug

- src/frontend/pages/ProjectDetailPage/project-edit-container/project-edit-container.test.tsx
- src/frontend/pages/ProjectDetailPage/project-edit-container/project-edit-container.tsx
- src/frontend/pages/ProjectDetailPage/project-edit-container/project-edit-details/project-edit-details.module.css
- src/frontend/pages/ProjectDetailPage/project-edit-container/project-edit-details/project-edit-details.test.tsx
- src/frontend/pages/ProjectDetailPage/project-edit-container/project-edit-details/project-edit-details.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-edit-container/work-package-edit-container.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-edit-container/work-package-edit-details/work-package-edit-details.tsx
Clean up styling and remove showing unnecessary shit on the project and work package edit forms.
old project edit form
project edit form is much more compact and properly formatted, also removed unnecessary shit.
old work package form
new work package edit form is much more compact, formatted properly, remove extra stuff
Closes #677
> #677 cleanup forms

- src/custom.scss
- src/frontend/layouts/page-block/page-block.module.css
- src/frontend/layouts/page-block/page-block.tsx
- src/frontend/pages/ChangeRequestsPage/change-requests-filter/change-requests-filter.module.scss
- src/frontend/pages/ChangeRequestsPage/change-requests-filter/change-requests-filter.tsx
- src/frontend/pages/ProjectDetailPage/project-view-container/work-package-summary/work-package-summary.module.scss
- src/frontend/pages/ProjectDetailPage/project-view-container/work-package-summary/work-package-summary.tsx
- src/frontend/pages/ProjectsPage/projects-table-filter/projects-table-filter.module.scss
- src/frontend/pages/ProjectsPage/projects-table-filter/projects-table-filter.tsx
> #388 fix styles

- src/frontend/layouts/page-block/page-block.tsx
- src/frontend/layouts/page-title/page-title.tsx
- src/frontend/pages/ChangeRequestDetailPage/change-request-details/change-request-details.test.tsx
- src/frontend/pages/ChangeRequestDetailPage/change-request-details/change-request-details.tsx
- src/frontend/pages/ChangeRequestDetailPage/change-request-details/type-specific-details/activation-details/activation-details.tsx
- src/frontend/pages/ChangeRequestDetailPage/change-request-details/type-specific-details/stage-gate-details/stage-gate-details.tsx
- src/frontend/pages/ChangeRequestDetailPage/change-request-details/type-specific-details/standard-details/standard-details.tsx
- src/frontend/pages/ChangeRequestsPage/change-requests-filter/change-requests-filter.module.scss
- src/frontend/pages/ChangeRequestsPage/change-requests-filter/change-requests-filter.tsx
- src/frontend/pages/ChangeRequestsPage/change-requests-table.module.css
- src/frontend/pages/ChangeRequestsPage/change-requests-table.tsx
- src/frontend/pages/ChangeRequestsPage/change-requests-table/change-requests-table.module.css
- src/frontend/pages/ChangeRequestsPage/change-requests-table/change-requests-table.tsx
- src/frontend/pages/HomePage/home.tsx
- src/frontend/pages/ProjectDetailPage/project-edit-container/project-edit-container.tsx
- src/frontend/pages/ProjectDetailPage/project-view-container/project-details/project-details.module.css
- src/frontend/pages/ProjectDetailPage/project-view-container/project-details/project-details.test.tsx
- src/frontend/pages/ProjectDetailPage/project-view-container/project-details/project-details.tsx
- src/frontend/pages/ProjectDetailPage/project-view-container/project-view-container.tsx
- src/frontend/pages/ProjectsPage/projects-table-filter/projects-table-filter.module.scss
- src/frontend/pages/ProjectsPage/projects-table-filter/projects-table-filter.tsx
- src/frontend/pages/ProjectsPage/projects-view.module.css
- src/frontend/pages/ProjectsPage/projects-view.tsx
- src/frontend/pages/SettingsPage/settings.test.tsx
- src/frontend/pages/SettingsPage/settings.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-edit-container/work-package-edit-container.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-view-container/work-package-details/work-package-details.module.css
- src/frontend/pages/WorkPackageDetailPage/work-package-view-container/work-package-details/work-package-details.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-view-container/work-package-view-container.tsx
- src/services/transformers/work-packages.transformers.ts
clean up a bunch of styling and organization of components
both tables now have much better responsive sizing:
extra large
small
fields dynamically readjust spacing
Closes #682
> #682 use grid

- src/frontend/pages/HomePage/home.tsx
changed name on homepage to be "Welcome, Firstname" instead of "Welcome, email"
> #608 - changed home page name to first name

- src/frontend/pages/SettingsPage/settings.tsx
Some fun experimenting with alert messaging
> #680 - experiment with alert messging

- package-lock.json
- package.json
Updated dependencies per build failure log provided by ITS on Friday, June 3, 2022.
```
5:53:24 PM: npm ERR! Missing: sass@^1.52.1
5:53:24 PM: npm ERR! Missing: typed-scss-modules@^6.4.1
```
Closes #697
> #697 - update dependencies

- src/frontend/pages/ChangeRequestDetailPage/change-request-details/change-request-details.tsx
- src/frontend/pages/ChangeRequestDetailPage/change-request-details/implemented-changes-list/implemented-changes-list.test.tsx
- src/frontend/pages/ChangeRequestDetailPage/change-request-details/implemented-changes-list/implemented-changes-list.tsx
- src/services/transformers/change-requests.transformers.ts
Fix the implemented changes list date implemented bug. Added display of overall CR date implemented.
- updated
- added one for new date display
Closes #707
> #707 fix implemented date bug

- src/frontend/app/app-authenticated/app-authenticated.tsx
- src/shared/routes.ts
Added super short redirect URL alias for change requests so users can use `nerpm.com/cr/10` to get to `nerpm.com/change-requests/10`. Tiny convenience tool.
Closes #710
> #710 - add super short cr url redirect

- package-lock.json
- package.json
- src/frontend/pages/ProjectDetailPage/project-view-container/project-gantt/project-gantt.module.css
- src/frontend/pages/ProjectDetailPage/project-view-container/project-gantt/project-gantt.test.tsx
- src/frontend/pages/ProjectDetailPage/project-view-container/project-gantt/project-gantt.tsx
- src/frontend/pages/ProjectDetailPage/project-view-container/project-view-container.tsx
- src/shared/chart-data.ts
Welp I added a Gantt chart. Couldn't seem to get the blue text and blue bars to be a different color though...
TODO: Contemplate life, consider adjusting text + bars to be NER Red, consider getting all backgrounds to match theme, then give up and just merge it.
I hate having to develop for `n` UIs. This doesn't work for dark mode. I couldn't get the types to line up properly.
Can't really test SVGs-built stuff
Dark mode fail:
Closes #596
> #596 project gantt

- src/backend/functions/users.ts
Quick and dirty sort of users. In back-end to avoid repeated sort in various areas of the front-end. Nothing actually relies on sort order and sort order from the database normally is just last edited so it really doesn't matter.
Closes #724
> #724 - sort users alphabetically

- src/backend/prisma/migrations/20220616215818_add_two_why_types/migration.sql
Fixing missed task from adding why types.
Closes #715
> #715 - create prisma migrations for new why types

- src/backend/functions/work-packages.ts
- src/frontend/pages/HomePage/home.test.tsx
- src/frontend/pages/HomePage/home.tsx
- src/frontend/pages/HomePage/upcoming-deadlines/upcoming-deadlines.module.css
- src/frontend/pages/HomePage/upcoming-deadlines/upcoming-deadlines.test.tsx
- src/frontend/pages/HomePage/upcoming-deadlines/upcoming-deadlines.tsx
- src/frontend/pages/HomePage/useful-links/useful-links.module.css
- src/frontend/pages/HomePage/useful-links/useful-links.tsx
- src/services/change-requests.api.ts
- src/services/change-requests.hooks.ts
- src/services/projects.api.ts
- src/services/projects.hooks.ts
- src/services/users.hooks.ts
- src/services/work-packages.api.ts
- src/services/work-packages.hooks.ts
- src/shared/pipes.tsx
- src/shared/urls.ts
- src/utils/src/api-routes.ts
Fixed some home page items, but mainly added the upcoming deadlines component and back-end endpoint to display relevant work packages in a quick but interconnected way to highlight the most important info to users. Got cool horizontal scroll working too. 
Will do timeline status component of this ticket in another separate PR since this got large.
Improved testing.
Closes #729
> #729 home smart features

- src/frontend/components/external-link/external-link.module.css
- src/frontend/components/external-link/external-link.test.tsx
- src/frontend/components/external-link/external-link.tsx
- src/frontend/components/wbs-status/wbs-status.module.css
- src/frontend/components/wbs-status/wbs-status.test.tsx
- src/frontend/components/wbs-status/wbs-status.tsx
- src/frontend/pages/HelpPage/HelpPage.tsx
- src/frontend/pages/HomePage/useful-links/useful-links.tsx
- src/frontend/pages/ProjectDetailPage/project-view-container/project-details/project-details.tsx
- src/frontend/pages/ProjectDetailPage/project-view-container/work-package-summary/work-package-summary.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-view-container/work-package-details/work-package-details.tsx
- src/shared/pipes.ts
- src/shared/pipes.tsx
- src/shared/tests/pipes.test.tsx
Changed around all the pipes to make equivalent react components. This feels more proper since a react component is just a function outputting JSX and having that be a pipe is just strange.
Still works!
Closes #738
> #738 components from pipes

- README.md
- docs/Deployment.md
- docs/ProductManagement.md
- package.json
- src/backend/prisma/manual.ts
Added script for writing and executing all manual database interactions, and added NPM command to run it easily.
Closes #727
> #727 manual database insertion

- src/backend/prisma/migrations/20220627165032_add_risks_model/migration.sql
- src/backend/prisma/schema.prisma
- src/backend/prisma/seed-data/risks.ts
- src/backend/prisma/seed.ts
- src/frontend/pages/WorkPackageDetailPage/stage-gate-work-package-modal-container/stage-gate-work-package-modal-container.test.tsx
Edited the prisma schema to incorporate the risk log
Closes # (issue #)
> #698 - edit schema

- src/frontend/pages/ProjectDetailPage/project-edit-container/project-edit-container.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-edit-container/work-package-edit-container.tsx
Removed forced page reloads
Closes #662
> #662 - Removed forced page reloads

- src/frontend/layouts/nav-top-bar/nav-user-menu/nav-user-menu.module.css
- src/frontend/layouts/nav-top-bar/nav-user-menu/nav-user-menu.tsx
The styling for the settings and logout button should be the same in practice now, their onClick area too should be the same.
**FINAL:**
_Any remaining things that need to get done_
Closes #406
> #406 - Logout Button Not Working

- src/backend/prisma/manual.ts
Basically just added various script helpers to the file.
Closes #780
> #780 prisma manual scripts

- src/frontend/pages/LoginPage/login-page.tsx
Decommission in favor of V3 FinishLine
> Decommission nerpm.netlify.app
