- docs/About.md
- docs/ContributorGuide.md
Closes #61 
1. About page had link to Docs vs docs
2. Contributor guide had broken links for 1st and last item
3. For the 1st item I think that & symbols are weird in links to section headers so changed it to an actual word
> #61-fixing broken things in docs 

- package-lock.json
- package.json
- src/App.tsx
- src/containers/projects-table/projects-table.test.tsx
- src/containers/projects-table/projects-table.tsx
- src/pages/projects/projects.test.tsx
- src/pages/projects/projects.tsx
- src/pages/wbs-details/wbs-details.module.css
- src/pages/wbs-details/wbs-details.test.tsx
- src/pages/wbs-details/wbs-details.tsx
- src/shared/test-utils.tsx
- src/utils/package-lock.json
- src/utils/package.json
- src/utils/src/index.ts
- src/utils/src/validate-wbs.ts
- src/utils/tests/validate-wbs.test.ts
Created a new page that will display either project details or work package details when given the WBS number. Reconfigured various different shared code, added WBS number validation from v1 repo, and the routing wiring to accommodate this new change. This change results in being able to click on rows in the projects table and be navigated to a page to see the details for the desired WBS number.
Projects table:
Navigated via click on row:
Navigated via direct URL navigation:
> Created Projects Detail Page to Display WBS

- src/pages/page-not-found/page-not-found.module.css
- src/pages/page-not-found/page-not-found.tsx
Removed the body tag from the 404 page not found component. Also went ahead and restyled the component, changed to using class names for CSS styling, and added top padding.
> Remove body tag and restyle 404 page

- src/components/change-request-details/change-request-details.module.css
- src/components/change-request-details/change-request-details.tsx
- src/components/change-requests-table/change-requests-table.module.css
- src/components/change-requests-table/change-requests-table.test.tsx
- src/components/change-requests-table/change-requests-table.tsx
- src/containers/change-requests-table/change-requests-table.module.css
- src/containers/change-requests-table/change-requests-table.test.tsx
- src/containers/change-requests-table/change-requests-table.tsx
- src/pages/change-request-details/change-request-details.module.css
- src/pages/change-request-details/change-request-details.test.tsx
- src/pages/change-request-details/change-request-details.tsx
- src/pages/change-requests/change-requests.test.tsx
- src/pages/change-requests/change-requests.tsx
Created the page for a single change request by wiring up the existing view component with a wrapper for fetching from the API, then also created the table for change requests to be displayed in, then the API fetching wrapper for that table of CRs, and finally wired together the change request routing pathways to ensure that proper front-end routes go to the proper places. Sorry for such a large PR. Closes #69. Closes #140.
> Created change request page and table page

- src/utils/src/api-utils.ts
- src/utils/src/dummy-data.ts
- src/utils/tests/api-utils.test.ts
- added check in route matcher
- prepends API_URL if not already prefix
- refined the error message accompanying the 404 to make debugging easier
- closes #172
> Ensure incoming request paths have API path prefix

- src/components/work-package-dependencies/work-package-dependencies.module.css
- src/components/work-package-dependencies/work-package-dependencies.test.tsx
- src/components/work-package-dependencies/work-package-dependencies.tsx
The component looks empty but it matches the other ones that were created. I can change the look of it but this what seemed to make the most sense. It is tested and should be ready to go. Closes #157
> #157 - Created dependencies component

- src/components/change-request-details/change-request-details.tsx
Remove unused imports to get rid of lint errors which were causing the deployment to fail.
> Remove unused imports

- package.json
- src/app/app-context/app-context.module.css
- src/app/app-context/app-context.test.tsx
- src/app/app-context/app-context.tsx
- src/app/app-core/app-core.module.css
- src/app/app-core/app-core.test.tsx
- src/app/app-core/app-core.tsx
- src/app/app-main/app-main.test.tsx
- src/app/app-main/app-main.tsx
- src/app/app-public/app-public.test.tsx
- src/app/app-public/app-public.tsx
- src/components/nav-user-menu/nav-user-menu.tsx
- src/pages/home/home.test.tsx
- src/pages/home/home.tsx
- src/pages/login/login.test.tsx
- src/pages/login/login.tsx
- src/setupTests.ts
- src/shared/routes.ts
- added lots of tests
- mock `localStorage` in tests
- split app section so context is separate from login logic
- enabled storage of userId in `localStorage`
- enable storage of page before login for redirect after login
- closes #221
> Enhance plain text login

- src/components/app/app-authenticated/app-authenticated.test.tsx
- src/components/app/app-context/app-context.test.tsx
- src/components/app/app-context/app-context.tsx
- src/components/app/app-core/app-core.test.tsx
- src/components/app/app-main/app-main.test.tsx
- src/components/app/app-main/app-main.tsx
- src/components/app/app-public/app-public.test.tsx
- src/components/change-requests/change-request-details/change-request-details.test.tsx
- src/components/change-requests/change-requests.test.tsx
- src/components/home/home.test.tsx
- src/components/projects/projects-table/projects-table.test.tsx
- src/components/projects/projects.test.tsx
- src/components/projects/wbs-details/project-container/project-container.test.tsx
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.test.tsx
- src/components/projects/wbs-details/wbs-details.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-changes/work-package-changes.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-dependencies/work-package-dependencies.test.tsx
- src/components/settings/settings.test.tsx
- src/components/whole-app/login/login.test.tsx
- src/components/whole-app/nav-top-bar/nav-notifications-menu/nav-notifications-menu.test.tsx
- src/components/whole-app/nav-top-bar/nav-page-links/nav-page-links.test.tsx
- src/components/whole-app/nav-top-bar/nav-top-bar.test.tsx
- src/components/whole-app/nav-top-bar/nav-user-menu/nav-user-menu.test.tsx
- src/test-support/test-utils.tsx
Lots of refactoring and figuring out what will work with what is needed. Shifted around routers and providers to better accommodate new pattern. Updated all tests to ensure robustness and passing. Closes #252.
> #252 - Refactor test utils and implement new wrapping/routing test util patterns

- src/backend/prisma/schema.prisma
- src/backend/prisma/seed-data/projects.ts
- src/backend/prisma/seed-data/work-packages.ts
- src/components/projects/wbs-details/project-container/project-details/project-details.tsx
- src/components/projects/wbs-details/project-container/rules-list/rules-list.test.tsx
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.test.tsx
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.tsx
- src/components/projects/wbs-details/work-package-container/work-package-details/work-package-details.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-details/work-package-details.tsx
- src/services/tests/projects.api.test.ts
- src/services/tests/work-packages.api.test.ts
- src/shared/tests/list-pipe.test.tsx
- src/test-support/test-data/projects.stub.ts
- src/test-support/test-data/work-packages.stub.ts
- src/utils/src/dummy-data.ts
- src/utils/src/types/project-types.ts
Moving budget from defined in work packages to just defined in projects. Also restyling the work package details to rebalance the two columns after removing the budget from that. Closes #301.
> #301 move budget

- src/backend/functions/projects.ts
- src/utils/src/api-routes.ts
Updated the Projects API endpoint to follow better design principles.
The API endpoint now uses the `apiRoutes` object, with the single project lookup function using `wbsNum` instead of `wbs`.
Signed-off-by: Lucas Sta Maria <lucas.stamaria@gmail.com>
> #243 - Update Projects API endpoint

- src/backend/functions/projects.ts
- src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
- src/components/change-requests/change-requests-table/change-requests-table.tsx
- src/components/projects/projects-table/projects-table.test.tsx
- src/components/projects/projects-table/projects-table.tsx
- src/components/projects/wbs-details/project-container/project-container.tsx
- src/components/projects/wbs-details/project-container/project-details/project-details.tsx
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.tsx
- src/components/projects/wbs-details/work-package-container/work-package-details/work-package-details.tsx
- src/services/projects.api.ts
- src/services/projects.hooks.ts
- src/shared/pipes.tsx
- src/test-support/test-data/projects.stub.ts
- src/utils/src/types/project-types.ts
Closes #357
We have added the projects transformer and updated the types to align the database and interfaces a bit more. We added a workPackageSummary type to replace the workPackage type on Projects, so projects is not transforming work packages and everything in them as well.
> #357 Project Shared Tools

- src/services/change-requests.api.ts
- src/services/projects.api.ts
- src/services/transformers/change-requests.transformers.ts
- src/services/transformers/projects.transformers.ts
- src/services/transformers/transformers.ts
- src/services/transformers/users.transformers.ts
- src/services/transformers/work-packages.transformers.ts
- src/services/users.api.ts
- src/services/work-packages.api.ts
We created a transformers folder and moved the change request transformer into it. We're not sure if we needed to do any tests for it because there weren't any previous tests for it. We are thinking about putting all transformer functions into one file.
> #302 moved change request transformer to separate transformer file

- src/components/change-requests/change-request-details/change-request-details/change-request-details.test.tsx
- src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
- src/services/tests/change-requests.api.test.ts
- src/test-support/test-data/change-requests.stub.ts
- src/utils/src/types/change-request-types.ts
Simple fix to the bug where it was looking for the incorrect field name. Closes #416 
front-end showing the field is now correctly displayed as true aka "YES"
Back-end showing the `confirmDone` field set to `true` for this CR
> Standardize stage gate CR field name to confirmDone

- src/components/change-requests/change-requests-table/change-requests-table/change-requests-table.tsx
Sort the CR table descending so newest submitted CRs are displayed first. Closes #415.
> Sort CR table desc

- src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
Added the condition that the approve and deny buttons show up only if the `accepted` column of a change request is not specified. This means that both approved and denied change requests won't have the buttons, but pending change requests will. Currently, the change request table doesn't indicate that a change request is denied, so it could be difficult to tell which change requests have already been reviewed.
Screenshot for approved CR:
Screenshot for denied CR:
Screenshot for pending CR:
> #431 - Add condition for when buttons appear

- src/components/change-requests/change-request-details/change-request-details/change-request-details.test.tsx
- src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
- src/components/change-requests/change-request-details/change-request-details/review-notes/review-notes.module.css
- src/components/change-requests/change-request-details/change-request-details/review-notes/review-notes.test.tsx
- src/components/change-requests/change-request-details/change-request-details/review-notes/review-notes.tsx
I added the review notes to be above the "Implemented Changes" list on the CR details page. Currently, it displays the review notes if they exist, and if there are no review notes, it fills the block in with a placeholder text. An alternative to this would be to conditionally show the review notes only if review notes exist for the change request. This could reduce the clutter of blocks on the page for change requests that haven't been reviewed yet. Let me know your thoughts about the alternative.
Has review notes:
Doesn't have review notes:
> #428 - Add review notes to details page

- src/backend/functions/projects-new.ts
- src/backend/tests/projects-new.test.ts
- src/utils/src/types/project-types.ts
The handler for creating a project was modified to take in `crId` since you create projects from change requests. I added helpers to get the max value of a project number for a specific `carNumber` and check if the specific change request was reviewed. Currently, the tests only ensure that the body of the input is valid and that the associated change request exists and has been reviewed. 
For checking if a change request exists, I currently have the helper pass down `null` to `baseHandler` if it doesn't exist and have the failure response returned there. I'm not sure if this is the preferred way of handling this error catching.
Also, for some reason, I had to specify the status to be `INACTIVE` even though it has a default value set in the prisma schema. Not sure if that's only for me …
> #366 - Add create project endpoint

- src/backend/functions/projects.ts
- src/components/projects/wbs-details/project-container/project-container.tsx
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.test.tsx
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.tsx
- src/services/transformers/projects.transformers.ts
- src/services/transformers/work-packages.transformers.ts
- src/utils/src/types/project-types.ts
In order to add deliverables and expected activities to the work package summary, I had to revert the several type usages from `WorkPackageSummary` back to `WorkPackage`.  I also had to modify the `workPackage` field on the `Project` type to use `WorkPackage[]` instead of `WorkPackageSummary[]`, which meant I had to do some modifications to the project transformer. I'm not completely sure I did the includes correctly, but it seems to work right now. I'm open to suggestions on how to improve the changes I made to the project transformer.
Note: @jamescd18 and I discussed how many deliverables and expected activities to display in the summary, and we decided on 3 being the max, which you will see reflected in the screenshots.
Screenshots of the new work package summary:
Work packages with 3 …
> #399 - Add deliverables & expected activities to wp summary

- src/components/change-requests/change-requests-table/change-requests-table.module.css
- src/components/change-requests/change-requests-table/change-requests-table.tsx
- src/components/projects/projects-table/projects-table.module.css
- src/components/projects/projects-table/projects-table.tsx
- src/components/shared/page-title/page-title.module.css
- src/components/shared/page-title/page-title.tsx
This is to fix the issue with horizontal scroll bars appearing in the `PageTitle` component when an `ActionButton` is added to it. This also fixes the issue with dropdown buttons being considered overflow and having a vertical scroll bar to look through those that was discovered in #354. As a result, we can open up another ticket to go back to our original plan of using dropdown buttons as opposed to having separate buttons for "Accept" and "Deny".
I made additional edits to the spacing on the Projects and CR home pages to get them to align correctly with the title, and also added an experimental bottom margin to see how that looked. I thought that the previous way of having the title and content really tight and close together didn't look the greatest so I wanted to try changing it up a …
> #418 page title overflow

- src/components/projects/create-wp-form/create-wp-form.tsx
- src/components/projects/create-wp-form/create-wp-form/create-wp-form.tsx
Start date validation is inherent by using a `type='date'` input. `validate` returns `true` if the project WBS # is valid and false if not. I put an input restriction on `duration`'s input to have a minimum possible value of 0. Beyond this, I'm not really sure how else to do the validation since we have no established pattern for doing form validation, so I feel this PR is only partially complete because I anticipate there being several changes made to the way I implemented the form validation.
> #496 Create Work Package Form Validation

- docs/Onboarding.md
I updated the section on how to get to VSCode 's `settings.json`, with the Command Palette as the default and two options from Settings.
> #516 - Revise Onboarding setup docs for VSCode 1.63.2 settings.json

- src/components/shared/page-block/page-block.module.css
Removed the scroll arrows from all text boxes by changing the overflow characteristics of the header where it's located
Changed this overflow property from auto to hidden to prevent any scroll arrows from existing
From trying out different options for headerRight text, it doesn't seem to cut off any of the text in headerRight (even multiline strings in this location); it just expands the size of the existing card. 
N/A
N/A
In Project
In Work Package
In Change Request
Completed
Please request reviewers and ping on slack only after you've …
> #403 - changed overflow for header from auto to hidden

- src/components/projects/projects-table/projects-table-filter/projects-table-filter.module.css
- src/components/projects/projects-table/projects-table-filter/projects-table-filter.test.tsx
- src/components/projects/projects-table/projects-table-filter/projects-table-filter.tsx
Added the clear button to the project filters. It resets the filters and the dropdown menus. Also added tests for it.
- tested that the clear button appears on the screen
- tested that the clear button changes filter values back to the defaults
Before clicking clear:
After clicking clear:
Closes #430
> #430 projects clear filters

- src/backend/functions/projects.ts
- src/backend/functions/work-packages.ts
- src/components/projects/wbs-details/work-package-container/work-package-details/work-package-details.test.tsx
- src/components/projects/wbs-details/work-package-container/work-package-details/work-package-details.tsx
- src/test-support/test-data/work-packages.stub.ts
- src/utils/src/backend-supports/projects-get-all.ts
- src/utils/src/types/project-types.ts
- src/utils/src/types/work-package-types.ts
- src/utils/tests/all-projects-support.test.ts
- Add TimelineStatus enum for work packages
- Create function to calculate timeline status from given progress and expectedProgress
- Add timeline status to work package front-end
Utils - calculateTimelineStatus:
- Ahead
- OnTrack
- OnTrack: progress = expectedProgress (edge case)
- Behind
- VeryBehind
Front End:
- Timeline Status in the document
Closes #479
> #479 - Implement Work Package Timeline Status

- src/components/change-requests/new-change-request/new-change-request-page/new-change-request-page.test.tsx
- src/components/change-requests/new-change-request/new-change-request-page/stage-gate-form-fileds/stage-gate-form-fields.test.tsx
- src/components/change-requests/new-change-request/new-change-request-page/stage-gate-form-fileds/stage-gate-form-fields.tsx
- src/components/change-requests/new-change-request/new-change-request.test.tsx
Removed the required reviewers text input for stage gate change requests.
n/a
Updated by removing tests.
n/a
Closes #484
> #484 - remove required reviewer

- docs/CreateReactApp.md
- package.json
“light-install” is a lighter alternative to npm install that avoids building unnecessary dependencies. This can be used for local development to cut down on development time. The script works by first running preinstall, which builds the packages in /utils. It then installs them into the global node_modules, ending by running postinstall to generate prisma.
> #417 - Create New "light-install" NPM Script

- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.module.css
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.test.tsx
- src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.tsx
Add link to "See N more..." at the bottom of Expected Activities and Deliverables lists on the work package preview on the project page. Link leads to the work package page.
Link is right-aligned and colored NER red using CSS. When hovered it will turn blue.
- No link when list length less than 3
- No link when list length is exactly 3
- Link appears when list length is greater than 3
In the given examples, only Expected Activities list is tested because all examples have only one Deliverable
Please request reviewers and ping on slack …
> #464 - Add Additional Bullets Count Link to Work Package Summary Accordion

- src/components/projects/projects-table/projects-table-filter/projects-table-filter.tsx
- src/components/projects/wbs-details/project-container/project-details/project-details.tsx
- src/components/projects/wbs-details/work-package-container/work-package-container-view/work-package-details/work-package-details.tsx
- src/shared/pipes.tsx
- src/shared/tests/pipes.test.tsx
Created a pipe for transforming a WBSElementStatus enum into a JSX.Element in the form of a bootstrap pill badge.
Closes #502
> #502 - Display Key Enum as Chips

- src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
display work package / project wbs number link on cr page
Closes #646
> #646 - display wbs link on cr details

- src/components/projects/wbs-details/project-page/project-edit-container/project-edit-container.tsx
- src/components/projects/wbs-details/project-page/project-edit-container/project-edit-details/project-edit-details.tsx
- src/components/projects/wbs-details/work-package-page/activate-work-package-modal-container/activate-work-package-modal-container.tsx
- src/components/projects/wbs-details/work-package-page/activate-work-package-modal-container/activate-work-package-modal/activate-work-package-modal.tsx
- src/components/projects/wbs-details/work-package-page/work-package-edit-container/work-package-edit-container.tsx
- src/components/projects/wbs-details/work-package-page/work-package-edit-container/work-package-edit-details/work-package-edit-details.tsx
change dropdowns to not include guest users.
see matching styling on selects and 6 users instead of 7
Closes #648
> #648 user dropdowns

- src/frontend/pages/ProjectDetailPage/project-view-container/work-package-summary/work-package-summary.module.css
- src/frontend/pages/ProjectDetailPage/project-view-container/work-package-summary/work-package-summary.tsx
Restyled / reorganized DOM elements to accommodate responsive design to display the work package status on the closed accordion.
Closes #669
> #669 - Reorganize DOM elements and display WP status on accordion

- src/frontend/pages/WorkPackageDetailPage/work-package-edit-container/work-package-edit-details/work-package-edit-details.tsx
Just added suffix weeks to work package edit form duration input
Closes #674
> #674 - specify weeks for work package edit form

- src/backend/functions/work-packages-create.ts
- src/backend/functions/work-packages-edit.ts
- src/backend/functions/work-packages.ts
Cut down on extraneous fields being sent back by the back-end by explicitly defining all the fields we want sent and not using the spread operator.
Closes #667
> #667 cut be fields

- src/backend/functions/change-requests.ts
Cut down on unneeded fields being sent back back-end to client by explicitly defining all fields sent back for change requests.
Closes #668
> #668 clean cr endpoints

- src/backend/functions/users.ts
Just cut out the spread operator to avoid leaking future user fields.
Closes #689
> #689 - cut spread operator from users endpoint

- src/frontend/app/app-main/app-main.tsx
- src/frontend/components/error-boundary/error-boundary.tsx
- src/frontend/pages/ErrorPage/error-page.tsx
- src/index.tsx
Implemented React Error Boundaries, so that when an unexpected error occurs in the application, a helpful error page is displayed to the user rather than a blank white page.
It might be worth looking into implementing this at specific points throughout the app in the future as an unexpected error in any child component of app-main will cause this display to pop up right now, but for now I think this implementation should help the users/us with debugging as more bugs start cropping up. The only notes I have are that I would appreciate any/all feedback on the design, I know it doesn't matter that much, but it looks kinda meh rn.
- Test that the error boundary causes an error page to  pop up when an error occurs in any of app-main's children.
It can be helpful to check the `Checks` and …
> #544 - Error Boundary

- src/backend/functions/change-requests-review.ts
Prevent reviewing your own CR in the back-end too
Review own CR response:
Closes #650
> #650 - add back-end check to prevent reviewing your own cr

- package-lock.json
- package.json
- src/frontend/app/app-authenticated/app-authenticated.tsx
- src/frontend/layouts/sidebar/sidebar.tsx
- src/frontend/pages/HelpPage/HelpPage.module.css
- src/frontend/pages/HelpPage/HelpPage.test.tsx
- src/frontend/pages/HelpPage/HelpPage.tsx
- src/frontend/pages/HomePage/useful-links/useful-links.test.tsx
- src/frontend/pages/HomePage/useful-links/useful-links.tsx
- src/shared/pipes.tsx
- src/shared/routes.ts
Added a new help page. Added icon link pipe for fancy looking links for fun.
I couldn't seem to get the types from `@fortawesome/free-brands-svg-icons` to work properly with the existing setup we have with fontawesome icons. Not even pulling in `@fortawesome/fontawesome-common-types` fixed the issue. So basically I gave up and chose different icons to represent Slack and GitHub. It kept saying the types are incompatible even when it really seemed like they were exactly the same types, but it's really tough given how it's some sorta enum of all possible options and I can't tell why it doesn't fit.
updated tests, tested help page loosely.
Please review the [contributor …
> #712 help page

- src/backend/functions/work-packages.ts
- src/frontend/pages/HomePage/home.test.tsx
- src/frontend/pages/HomePage/home.tsx
- src/frontend/pages/HomePage/work-packages-by-timeline-status/work-packages-by-timeline-status.module.css
- src/frontend/pages/HomePage/work-packages-by-timeline-status/work-packages-by-timeline-status.test.tsx
- src/frontend/pages/HomePage/work-packages-by-timeline-status/work-packages-by-timeline-status.tsx
- src/services/work-packages.api.ts
- src/services/work-packages.hooks.ts
- src/shared/urls.ts
Expanded the existing work packages get all endpoint to support optional filtering by status and/or timeline status, not via Prisma implementation. Expanded get all work packages hook to support this filtering. Use this filtering to add a "Work Packages by Timeline Status" component to the home page which not only displays all "VERY_BEHIND" work packages by default, but also allows users to select to see work packages with a different timeline status. Uses the same horizontal scroll card format as the upcoming deadlines component.
Okay so this one was interestingly tough. I first filtered client-side until I realized that messes up the loading and isn't so proper, then considered a whole new endpoint, but decided not to. I experiment and researched and built out a flexible addition to the …
> #729 timeline status home

- src/backend/functions/work-packages.ts
- src/frontend/layouts/nav-top-bar/nav-top-bar.tsx
- src/frontend/pages/HomePage/upcoming-deadlines/upcoming-deadlines.test.tsx
- src/frontend/pages/HomePage/upcoming-deadlines/upcoming-deadlines.tsx
- src/frontend/pages/HomePage/work-packages-by-timeline-status/work-packages-by-timeline-status.test.tsx
- src/frontend/pages/HomePage/work-packages-by-timeline-status/work-packages-by-timeline-status.tsx
- src/frontend/pages/LoginPage/login.tsx
- src/services/work-packages.api.ts
- src/services/work-packages.hooks.ts
- src/shared/pipes.tsx
- src/shared/tests/urls.test.tsx
- src/shared/urls.ts
- src/utils/src/api-routes.ts
Okay so basically I did all the adjustments that I wanted to do from my last PR and some more cuz cleanup is good whatever lol. Turns out I could get rid of the useEffect hook refetch if I just had a flexible object for query parameters instead of function parameters. I expended the work package endpoint to have enough query parameters to replace the separate upcoming deadlines endpoint so that's good. Also had to ensure that query params were included in query keys or else it would use the same resulting data for both instances of the same hook no matter the input. Good to know `react-query` is smart.
improved testing by testing the url function for work package query parameters urls
Now that's a proper home page
Please …
> #729 home adjustments

- src/frontend/layouts/page-breadcrumbs/page-breadcrumbs.module.css
- src/frontend/layouts/page-breadcrumbs/page-breadcrumbs.test.tsx
- src/frontend/layouts/page-breadcrumbs/page-breadcrumbs.tsx
- src/frontend/layouts/page-title/page-title.tsx
- src/frontend/layouts/sidebar/nav-page-links/nav-page-links.test.tsx
- src/frontend/layouts/sidebar/nav-page-links/nav-page-links.tsx
- src/frontend/layouts/sidebar/sidebar.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-page.test.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-view-container/work-package-view-container.test.tsx
- src/frontend/pages/WorkPackageDetailPage/work-package-view-container/work-package-view-container.tsx
- src/shared/types.ts
- src/test-support/test-data/test-utils.stub.ts
Added breadcrumbs to the work package page because work packages are the most stranded page compared to the rest.
Closes #745
> #745 breadcrumbs

- src/backend/functions/risks.ts
- src/utils/src/api-routes.ts
- src/utils/src/index.ts
- src/utils/src/types/project-types.ts
- src/utils/src/types/risk-types.ts
- src/utils/src/types/user-types.ts
Added a risks.ts file and the get risks by project id endpoint
it can be argued that this endpoint is unneeded and should be part of the return values of projects. That could be true, but this prevents changing a lot of code which is nice. I also just wanted the risks.ts file to be up and running for some of the other prs and stuff
manually tested that it works when I go to localhost:3000/.netlify/functions/risks/2 -- didn't try with any data though lol
Closes #767
> #767 - Risks.ts file and getRisks
